export const categorizedStores = [
  {
    id: [
      1001, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1014, 1018, 1019, 1022, 1024, 1025, 1028, 1029,
      1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1039, 1042, 1043, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052,
      1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061,
    ],
    name: 'Alle',
    checked: true,
    category: 'adjusted',
    categoryKey: 'all',
    key: 'all',
    group: 'General',
  },
  {
    id: [
      1001, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1014, 1018, 1019, 1022, 1024, 1025, 1028, 1029,
      1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1039, 1042, 1043, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052,
      1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061,
    ],
    name: 'Bereinigt',
    checked: true,
    category: 'adjusted',
    categoryKey: 'adjusted',
    key: 'adjusted',
    group: 'General',
  },
  {
    name: 'Center (100)',
    category: 'Filialtyp',
    categoryKey: 'type',
    checked: true,
    id: [1007, 1008],
    key: 'type-Center (100)',
    group: 'Filialtyp',
  },
  {
    name: 'Center Brotläden',
    category: 'Filialtyp',
    categoryKey: 'type',
    checked: true,
    id: [1004, 1060],
    key: 'type-Center Brotläden',
    group: 'Filialtyp',
  },
  {
    name: 'Deli-Markt',
    category: 'Filialtyp',
    categoryKey: 'type',
    checked: true,
    id: [1045],
    key: 'type-Deli-Markt',
    group: 'Filialtyp',
  },
  {
    name: 'Freestander Deli (125)',
    category: 'Filialtyp',
    categoryKey: 'type',
    checked: true,
    id: [1012, 1031, 1033, 1034, 1035, 1053, 1056, 1059],
    key: 'type-Freestander Deli (125)',
    group: 'Filialtyp',
  },
  {
    name: 'Freestander nah (120)',
    category: 'Filialtyp',
    categoryKey: 'type',
    checked: true,
    id: [1019, 1030, 1032, 1058],
    key: 'type-Freestander nah (120)',
    group: 'Filialtyp',
  },
  {
    name: 'Freestander Umsatzschwelle',
    category: 'Filialtyp',
    categoryKey: 'type',
    checked: true,
    id: [1029, 1048, 1049, 1055, 1057],
    key: 'type-Freestander Umsatzschwelle',
    group: 'Filialtyp',
  },
  {
    name: 'Hoher im Haus/Cafe Anteil (130)',
    category: 'Filialtyp',
    categoryKey: 'type',
    checked: true,
    id: [1006, 1009, 1047],
    key: 'type-Hoher im Haus/Cafe Anteil (130)',
    group: 'Filialtyp',
  },
  {
    name: 'Innenstadt (110)',
    category: 'Filialtyp',
    categoryKey: 'type',
    checked: true,
    id: [1001, 1037, 1039, 1042],
    key: 'type-Innenstadt (110)',
    group: 'Filialtyp',
  },
  {
    name: 'Vorkassen (140)',
    category: 'Filialtyp',
    categoryKey: 'type',
    checked: true,
    id: [1005, 1010, 1011, 1014, 1018, 1022, 1028, 1043, 1050, 1051, 1052, 1061],
    key: 'type-Vorkassen (140)',
    group: 'Filialtyp',
  },
  {
    name: 'nicht zugewiesen',
    category: 'Filialtyp',
    categoryKey: 'type',
    checked: true,
    id: [1003, 1024, 1025, 1036, 1046, 1054],
    key: 'type-nz-type',
    group: 'Filialtyp',
  },
  {
    name: 'mathias.pidun@evertzberg.de',
    category: 'Verkaufsgebiet',
    categoryKey: 'manager',
    checked: true,
    id: [1001, 1005, 1008, 1011, 1012, 1022, 1024, 1025, 1035, 1042, 1046, 1052, 1055, 1058],
    key: 'manager-mathias.pidun@evertzberg.de',
    group: 'Verkaufsgebiet',
  },
  {
    name: 'sebastian.teske@evertzberg.de',
    category: 'Verkaufsgebiet',
    categoryKey: 'manager',
    checked: true,
    id: [1031, 1034, 1036, 1039, 1045, 1050, 1051, 1054, 1056, 1060],
    key: 'manager-sebastian.teske@evertzberg.de',
    group: 'Verkaufsgebiet',
  },
  {
    name: 'Tiziana.DelloBuono@evertzberg.de',
    category: 'Verkaufsgebiet',
    categoryKey: 'manager',
    checked: true,
    id: [1019, 1028, 1030, 1037, 1043, 1048, 1049, 1053, 1057, 1059],
    key: 'manager-Tiziana.DelloBuono@evertzberg.de',
    group: 'Verkaufsgebiet',
  },
  {
    name: 'nicht zugewiesen',
    category: 'Verkaufsgebiet',
    categoryKey: 'manager',
    checked: true,
    id: [1003, 1004, 1006, 1007, 1009, 1010, 1014, 1018, 1029, 1032, 1033, 1047, 1061],
    key: 'manager-nz-manager',
    group: 'Verkaufsgebiet',
  },
  {
    id: 1001,
    name: '1001 | Wermelskirchen',
    address: 'Telegrafenstraße 42, 42929 Wermelskirchen',
    lat: 51.140952,
    lon: 7.2140908,
    adjusted: true,
    type: 'Innenstadt (110)',
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1001',
    group: 'Filialen',
  },
  {
    id: 1003,
    name: '1003 | Henkelshof',
    address: 'Hans-Potyka-Straße 8, 42897 Remscheid',
    lat: 51.19812,
    lon: 7.27445,
    adjusted: true,
    type: null,
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1003',
    group: 'Filialen',
  },
  {
    id: 1004,
    name: '1004 | Center Köln-Chorweiler',
    address: ', 50765 Köln',
    lat: 51.0242454,
    lon: 6.879553,
    adjusted: true,
    type: 'Center Brotläden',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1004',
    group: 'Filialen',
  },
  {
    id: 1005,
    name: '1005 | Edeka Witzhelden',
    address: 'Solinger Str. 7, 42799 Leichlingen-Witzhelden',
    lat: 51.1173106,
    lon: 7.1103004,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1005',
    group: 'Filialen',
  },
  {
    id: 1006,
    name: '1006 | Vennhauser Allee',
    address: 'Vennhauser Allee 254, 40627 Düsseldorf',
    lat: 51.2136097,
    lon: 6.863792999999999,
    adjusted: true,
    type: 'Hoher im Haus/Cafe Anteil (130)',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1006',
    group: 'Filialen',
  },
  {
    id: 1007,
    name: '1007 | Allee-Center',
    address: 'Alleestraße 74, 42853 Remscheid',
    lat: 51.1825217,
    lon: 7.1881134,
    adjusted: true,
    type: 'Center (100)',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1007',
    group: 'Filialen',
  },
  {
    id: 1008,
    name: '1008 | City-Arkaden',
    address: 'Alte Freiheit 9, 42103 Wuppertal',
    lat: 51.2575878,
    lon: 7.1504568,
    adjusted: true,
    type: 'Center (100)',
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1008',
    group: 'Filialen',
  },
  {
    id: 1009,
    name: '1009 | Fritz-Reuter-Straße',
    address: 'Fritz-Reuter-Straße 17, 42897 Remscheid',
    lat: 51.1945548,
    lon: 7.2705774,
    adjusted: true,
    type: 'Hoher im Haus/Cafe Anteil (130)',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1009',
    group: 'Filialen',
  },
  {
    id: 1010,
    name: '1010 | Edeka Hasten',
    address: 'Königsstraße 203, 42853 Remscheid',
    lat: 51.1908227,
    lon: 7.1673207,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1010',
    group: 'Filialen',
  },
  {
    id: 1011,
    name: '1011 | Belten',
    address: 'Im Belten 2, 42929 Wermelskirchen',
    lat: 51.1468478,
    lon: 7.2336181,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1011',
    group: 'Filialen',
  },
  {
    id: 1012,
    name: '1012 | Heckinghausen',
    address: 'Heckinghauser Str. 133, 42289 Wuppertal',
    lat: 51.2714458,
    lon: 7.2182753,
    adjusted: true,
    type: 'Freestander Deli (125)',
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1012',
    group: 'Filialen',
  },
  {
    id: 1014,
    name: '1014 | Dabringhausen',
    address: 'Südstraße 6, 42929 Wermelskirchen',
    lat: 51.09080609999999,
    lon: 7.186796299999999,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1014',
    group: 'Filialen',
  },
  {
    id: 1018,
    name: '1018 | Lüttringhausen',
    address: 'Am Schützenplatz 16, 42899 Remscheid',
    lat: 51.21262,
    lon: 7.2351,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1018',
    group: 'Filialen',
  },
  {
    id: 1019,
    name: '1019 | Mollenkotten',
    address: 'Mollenkotten 8-10, 42279 Wuppertal',
    lat: 51.3023728,
    lon: 7.2165047,
    adjusted: true,
    type: 'Freestander nah (120)',
    manager: 'Tiziana.DelloBuono@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1019',
    group: 'Filialen',
  },
  {
    id: 1022,
    name: '1022 | Wipperfürth',
    address: 'Hindenburgstraße 2, 51688 Wipperfürth',
    lat: 51.1175299,
    lon: 7.4006529,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1022',
    group: 'Filialen',
  },
  {
    id: 1024,
    name: '1024 | Wittener Straße',
    address: 'Wittener Straße 16, 42277 Wuppertal',
    lat: 51.286514,
    lon: 7.2313363,
    adjusted: true,
    type: null,
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1024',
    group: 'Filialen',
  },
  {
    id: 1025,
    name: '1025 | _Tente (Edeka-Markt)',
    address: 'Tente 49, 42929 Wermelskirchen',
    lat: 51.1237075,
    lon: 7.1943813,
    adjusted: true,
    type: null,
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: false,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1025',
    group: 'Filialen',
  },
  {
    id: 1028,
    name: '1028 | REWE Haan',
    address: 'Hochdahler Str. 2, 42781 Haan',
    lat: 51.1871255,
    lon: 6.990364,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: 'Tiziana.DelloBuono@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1028',
    group: 'Filialen',
  },
  {
    id: 1029,
    name: '1029 | RS-Burger Str.',
    address: 'Burger Str. 19, 42859 Remscheid',
    lat: 51.1723243,
    lon: 7.2077094,
    adjusted: true,
    type: 'Freestander Umsatzschwelle',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1029',
    group: 'Filialen',
  },
  {
    id: 1030,
    name: '1030 | Hahnerberg',
    address: 'Hahnerberger Str. 185, 42349 Wuppertal',
    lat: 51.2202249,
    lon: 7.1526163,
    adjusted: true,
    type: 'Freestander nah (120)',
    manager: 'Tiziana.DelloBuono@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1030',
    group: 'Filialen',
  },
  {
    id: 1031,
    name: '1031 | Erkrath',
    address: 'Neanderstraße 50, 40699 Erkrath',
    lat: 51.224892,
    lon: 6.9075861,
    adjusted: true,
    type: 'Freestander Deli (125)',
    manager: 'sebastian.teske@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1031',
    group: 'Filialen',
  },
  {
    id: 1032,
    name: '1032 | SG-Schützenstraße',
    address: 'Schützenstr. 91, 42999 Solingen',
    lat: 51.1631649,
    lon: 7.0962947,
    adjusted: true,
    type: 'Freestander nah (120)',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1032',
    group: 'Filialen',
  },
  {
    id: 1033,
    name: '1033 | SG-Anfangstraße',
    address: 'Anfangstraße 2, 42697 Solingen',
    lat: 51.1613713,
    lon: 6.9942463,
    adjusted: true,
    type: 'Freestander Deli (125)',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1033',
    group: 'Filialen',
  },
  {
    id: 1034,
    name: '1034 | Nevigeser Straße',
    address: 'Nevigeser Str. 15, 42113 Wuppertal',
    lat: 51.2679617,
    lon: 7.1280751,
    adjusted: true,
    type: 'Freestander Deli (125)',
    manager: 'sebastian.teske@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1034',
    group: 'Filialen',
  },
  {
    id: 1035,
    name: '1035 | WK-Neuenhöhe',
    address: 'Neuenhöhe 23 - 25, 42929 Wermelskirchen',
    lat: 51.14661,
    lon: 7.23621,
    adjusted: true,
    type: 'Freestander Deli (125)',
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1035',
    group: 'Filialen',
  },
  {
    id: 1036,
    name: '1036 | _Solingen-Wald',
    address: 'Friedrich-Ebert-Straße 136, 42719 Solingen',
    lat: 51.184203,
    lon: 7.0419818,
    adjusted: true,
    type: null,
    manager: 'sebastian.teske@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1036',
    group: 'Filialen',
  },
  {
    id: 1037,
    name: '1037 | Solingen-Ohligs',
    address: 'Düsseldorfer Straße 63, 42697 Solingen',
    lat: 51.16212,
    lon: 6.99878,
    adjusted: true,
    type: 'Innenstadt (110)',
    manager: 'Tiziana.DelloBuono@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1037',
    group: 'Filialen',
  },
  {
    id: 1039,
    name: '1039 | Kölner Straße',
    address: 'Kölner Straße 88, 42651 Solingen',
    lat: 51.1712735,
    lon: 7.0830924,
    adjusted: true,
    type: 'Innenstadt (110)',
    manager: 'sebastian.teske@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1039',
    group: 'Filialen',
  },
  {
    id: 1042,
    name: '1042 | Schwelm',
    address: 'Hauptstraße 70, 58332 Schwelm',
    lat: 51.28454,
    lon: 7.29575,
    adjusted: true,
    type: 'Innenstadt (110)',
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1042',
    group: 'Filialen',
  },
  {
    id: 1043,
    name: '1043 | Hilden (Edeka-Markt)',
    address: 'Walder Straße 99, 40724 Hilden',
    lat: 51.1691322,
    lon: 6.9522711,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: 'Tiziana.DelloBuono@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1043',
    group: 'Filialen',
  },
  {
    id: 1045,
    name: '1045 | Wochenmarkt Carlsplatz',
    address: 'Carlsplatz 14, 40213 Düsseldorf',
    lat: 51.2233331,
    lon: 6.7743864,
    adjusted: true,
    type: 'Deli-Markt',
    manager: 'sebastian.teske@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1045',
    group: 'Filialen',
  },
  {
    id: 1046,
    name: '1046 | _Naturgut Gevelsberg',
    address: 'Hagener Str. 215, 58285 Gevelsberg',
    lat: 51.329105,
    lon: 7.366195,
    adjusted: true,
    type: null,
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1046',
    group: 'Filialen',
  },
  {
    id: 1047,
    name: '1047 | Genuss hoch 3',
    address: 'Freiheitstr. 70, 42853 Remscheid',
    lat: 51.1778959,
    lon: 7.1910855,
    adjusted: true,
    type: 'Hoher im Haus/Cafe Anteil (130)',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1047',
    group: 'Filialen',
  },
  {
    id: 1048,
    name: '1048 | Lev-Lützenkirchen',
    address: 'Lützenkirchener Straße 166, 51381 Leverkusen',
    lat: 51.0667918,
    lon: 7.0240268,
    adjusted: true,
    type: 'Freestander Umsatzschwelle',
    manager: 'Tiziana.DelloBuono@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1048',
    group: 'Filialen',
  },
  {
    id: 1049,
    name: '1049 | Leichlingen',
    address: 'Roßlenbruch 5, 42799 Leichlingen',
    lat: 51.1043316,
    lon: 6.9994511,
    adjusted: true,
    type: 'Freestander Umsatzschwelle',
    manager: 'Tiziana.DelloBuono@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1049',
    group: 'Filialen',
  },
  {
    id: 1050,
    name: '1050 | Wülfrath',
    address: 'Goethestraße 19 - 21, 42489 Wülfrath',
    lat: 51.2802011,
    lon: 7.0346699,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: 'sebastian.teske@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1050',
    group: 'Filialen',
  },
  {
    id: 1051,
    name: '1051 | Hofgarten-Center',
    address: 'Kölner Straße 99, 42651 Solingen',
    lat: 51.1713051,
    lon: 7.0818558,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: 'sebastian.teske@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1051',
    group: 'Filialen',
  },
  {
    id: 1052,
    name: '1052 | EDEKA-Radevormwald',
    address: 'Elberfelder Straße 94 - 96, 42477 Radevormwald',
    lat: 51.2024828,
    lon: 7.3339095,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1052',
    group: 'Filialen',
  },
  {
    id: 1053,
    name: '1053 | Solingen Aufderhöhe',
    address: 'Aufderhöher Str. 147, 42699 Solingen',
    lat: 51.1396274,
    lon: 7.0130084,
    adjusted: true,
    type: 'Freestander Deli (125)',
    manager: 'Tiziana.DelloBuono@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1053',
    group: 'Filialen',
  },
  {
    id: 1054,
    name: '1054 | Barmen-Werth',
    address: 'Werth 18, 42275 Wuppertal',
    lat: 51.270878,
    lon: 7.1988516,
    adjusted: true,
    type: null,
    manager: 'sebastian.teske@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1054',
    group: 'Filialen',
  },
  {
    id: 1055,
    name: '1055 | Ronsdorf',
    address: 'Erbschlöerstr. 19, 42369 Wuppertal',
    lat: 51.2275674,
    lon: 7.2038036,
    adjusted: true,
    type: 'Freestander Umsatzschwelle',
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1055',
    group: 'Filialen',
  },
  {
    id: 1056,
    name: '1056 | SG-Spitzweg',
    address: 'Spitzwegstr. 1, 42719 Solingen',
    lat: 51.1799752,
    lon: 7.0362926,
    adjusted: true,
    type: 'Freestander Deli (125)',
    manager: 'sebastian.teske@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1056',
    group: 'Filialen',
  },
  {
    id: 1057,
    name: '1057 | Langenfeld',
    address: 'Schneiderstr. 2, 40764 Langenfeld',
    lat: 51.1188932,
    lon: 6.9706822,
    adjusted: true,
    type: 'Freestander Umsatzschwelle',
    manager: 'Tiziana.DelloBuono@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1057',
    group: 'Filialen',
  },
  {
    id: 1058,
    name: '1058 | in den Birgden 2',
    address: ', 42929 Wermelskirchen',
    lat: 51.1030829,
    lon: 7.2240777,
    adjusted: true,
    type: 'Freestander nah (120)',
    manager: 'mathias.pidun@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1058',
    group: 'Filialen',
  },
  {
    id: 1059,
    name: '1059 | SG Merscheid',
    address: 'Merscheider Straße 108, 42699 Solingen',
    lat: 51.1639737,
    lon: 7.0208106,
    adjusted: true,
    type: 'Freestander Deli (125)',
    manager: 'Tiziana.DelloBuono@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1059',
    group: 'Filialen',
  },
  {
    id: 1060,
    name: '1060 | Altenessen',
    address: 'Altenessener Straße 411, 45329 Essen',
    lat: 51.4965634,
    lon: 7.0071631,
    adjusted: true,
    type: 'Center Brotläden',
    manager: 'sebastian.teske@evertzberg.de',
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1060',
    group: 'Filialen',
  },
  {
    id: 1061,
    name: '1061 | EDEKA Lennep',
    address: 'Kölner Straße 38, 42897 Remscheid',
    lat: 51.1907262,
    lon: 7.2570231,
    adjusted: true,
    type: 'Vorkassen (140)',
    manager: null,
    relevant_in_sales: true,
    active_in: ['bestell-tuning', 'filial-tuning', 'filial-radar'],
    allowed_products: ['bestell-tuning', 'filial-tuning'],
    preselect_in: ['bestell-tuning', 'filial-tuning'],
    checked: true,
    category: 'all',
    key: 'all-1061',
    group: 'Filialen',
  },
]
